# Site settings
title: "Name"
description: "A brief description of your resume"
baseurl: "" # leave empty
url: "https://ManKrei.github.io"
theme: jekyll-devportfolio

# Navigation settings
navigation:
  - title: "About"
    url: "/"
  - title: "Education"
    url: "/education"
  - title: "Experience"
    url: "/experience"
  - title: "Skills"
    url: "/skills"
  - title: "Interests"
    url: "/interests"

# Personal Information
name: Your Name
email: your.email@example.com
github_username: your-github-username
linkedin_username: your-linkedin-username
